version: '3'
services:
  web:
    build: ./web
    ports:
      - "8888:8888"
    depends_on:
      - database
      - cache 
  database:
      build: ./database
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydb
      ports:
        - "5432:5432"
      volumes:
        # Mount init.sql so Postgres runs it at first startup
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  cache:
      build: ./cache